# Railway configuration with Browserless
# Browserless handles Chrome installation automatically
# https://railway.app/template/browserless

services:
  # Browserless service (handles Chrome automatically)
  browserless:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    environment:
      - CHROME_HEADLESS=true
      - CONNECTION_TIMEOUT=30000
      - ENABLE_DEBUGGER=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python FastAPI scraper app
  web-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BROWSERLESS_URL=http://browserless:3000/webdriver
      - PYTHONUNBUFFERED=1
      - PORT=8000
    depends_on:
      browserless:
        condition: service_healthy
    volumes:
      - ./excel_files:/app/excel_files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
